environment: development
log_level: info

gateway:
  port: 8080
  timeout: 30s

services:
  search:
    host: localhost
    port: 8081
    timeout: 10s
  
  tokenizer:
    host: localhost
    port: 8090
    timeout: 5s
  
  inference:
    host: localhost
    port: 8083
    timeout: 30s
  
  safety:
    host: localhost
    port: 8084
    timeout: 5s
  
  llm:
    host: localhost
    port: 8086
    timeout: 30s

google:
  api_key: ""  # Set via GOOGLE_API_KEY environment variable
  cx: ""       # Set via GOOGLE_CX environment variable 