// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/search.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common messages
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Search messages
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	SafeSearch    bool                   `protobuf:"varint,2,opt,name=safe_search,json=safeSearch,proto3" json:"safe_search,omitempty"`
	NumResults    int32                  `protobuf:"varint,3,opt,name=num_results,json=numResults,proto3" json:"num_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetSafeSearch() bool {
	if x != nil {
		return x.SafeSearch
	}
	return false
}

func (x *SearchRequest) GetNumResults() int32 {
	if x != nil {
		return x.NumResults
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	DisplayUrl    string                 `protobuf:"bytes,4,opt,name=display_url,json=displayUrl,proto3" json:"display_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SearchResult) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *SearchResult) GetDisplayUrl() string {
	if x != nil {
		return x.DisplayUrl
	}
	return ""
}

// Inference messages
type SummarizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalText  string                 `protobuf:"bytes,1,opt,name=original_text,json=originalText,proto3" json:"original_text,omitempty"`
	Streaming     bool                   `protobuf:"varint,2,opt,name=streaming,proto3" json:"streaming,omitempty"`
	MaxLength     int32                  `protobuf:"varint,3,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeRequest) Reset() {
	*x = SummarizeRequest{}
	mi := &file_proto_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeRequest) ProtoMessage() {}

func (x *SummarizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeRequest.ProtoReflect.Descriptor instead.
func (*SummarizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{5}
}

func (x *SummarizeRequest) GetOriginalText() string {
	if x != nil {
		return x.OriginalText
	}
	return ""
}

func (x *SummarizeRequest) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *SummarizeRequest) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

type SummarizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeResponse) Reset() {
	*x = SummarizeResponse{}
	mi := &file_proto_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeResponse) ProtoMessage() {}

func (x *SummarizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeResponse.ProtoReflect.Descriptor instead.
func (*SummarizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{6}
}

func (x *SummarizeResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SummarizeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SummarizeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SummarizeResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *SummarizeResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type SummarizeStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeStreamResponse) Reset() {
	*x = SummarizeStreamResponse{}
	mi := &file_proto_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeStreamResponse) ProtoMessage() {}

func (x *SummarizeStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeStreamResponse.ProtoReflect.Descriptor instead.
func (*SummarizeStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{7}
}

func (x *SummarizeStreamResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SummarizeStreamResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *SummarizeStreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SummarizeStreamResponse) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

// Safety messages
type ValidateInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	SafeSearch    bool                   `protobuf:"varint,3,opt,name=safe_search,json=safeSearch,proto3" json:"safe_search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateInputRequest) Reset() {
	*x = ValidateInputRequest{}
	mi := &file_proto_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateInputRequest) ProtoMessage() {}

func (x *ValidateInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateInputRequest.ProtoReflect.Descriptor instead.
func (*ValidateInputRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateInputRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ValidateInputRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *ValidateInputRequest) GetSafeSearch() bool {
	if x != nil {
		return x.SafeSearch
	}
	return false
}

type ValidateInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSafe        bool                   `protobuf:"varint,1,opt,name=is_safe,json=isSafe,proto3" json:"is_safe,omitempty"`
	SanitizedText string                 `protobuf:"bytes,2,opt,name=sanitized_text,json=sanitizedText,proto3" json:"sanitized_text,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateInputResponse) Reset() {
	*x = ValidateInputResponse{}
	mi := &file_proto_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateInputResponse) ProtoMessage() {}

func (x *ValidateInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateInputResponse.ProtoReflect.Descriptor instead.
func (*ValidateInputResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateInputResponse) GetIsSafe() bool {
	if x != nil {
		return x.IsSafe
	}
	return false
}

func (x *ValidateInputResponse) GetSanitizedText() string {
	if x != nil {
		return x.SanitizedText
	}
	return ""
}

func (x *ValidateInputResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ValidateInputResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SanitizeOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanitizeOutputRequest) Reset() {
	*x = SanitizeOutputRequest{}
	mi := &file_proto_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeOutputRequest) ProtoMessage() {}

func (x *SanitizeOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeOutputRequest.ProtoReflect.Descriptor instead.
func (*SanitizeOutputRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{10}
}

func (x *SanitizeOutputRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SanitizeOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SanitizedText string                 `protobuf:"bytes,1,opt,name=sanitized_text,json=sanitizedText,proto3" json:"sanitized_text,omitempty"`
	Warnings      []string               `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanitizeOutputResponse) Reset() {
	*x = SanitizeOutputResponse{}
	mi := &file_proto_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeOutputResponse) ProtoMessage() {}

func (x *SanitizeOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeOutputResponse.ProtoReflect.Descriptor instead.
func (*SanitizeOutputResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{11}
}

func (x *SanitizeOutputResponse) GetSanitizedText() string {
	if x != nil {
		return x.SanitizedText
	}
	return ""
}

func (x *SanitizeOutputResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *SanitizeOutputResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// LLM Orchestrator messages
type LLMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Stream        bool                   `protobuf:"varint,4,opt,name=stream,proto3" json:"stream,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMRequest) Reset() {
	*x = LLMRequest{}
	mi := &file_proto_search_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRequest) ProtoMessage() {}

func (x *LLMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRequest.ProtoReflect.Descriptor instead.
func (*LLMRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{12}
}

func (x *LLMRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LLMRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *LLMRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *LLMRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *LLMRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type LLMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tokens        []string               `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Complete      bool                   `protobuf:"varint,5,opt,name=complete,proto3" json:"complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMResponse) Reset() {
	*x = LLMResponse{}
	mi := &file_proto_search_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMResponse) ProtoMessage() {}

func (x *LLMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMResponse.ProtoReflect.Descriptor instead.
func (*LLMResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{13}
}

func (x *LLMResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LLMResponse) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *LLMResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *LLMResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LLMResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

type LLMStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMStatusRequest) Reset() {
	*x = LLMStatusRequest{}
	mi := &file_proto_search_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMStatusRequest) ProtoMessage() {}

func (x *LLMStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMStatusRequest.ProtoReflect.Descriptor instead.
func (*LLMStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{14}
}

func (x *LLMStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type LLMStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // pending, processing, completed, failed
	QueuePosition     int32                  `protobuf:"varint,3,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	EstimatedWaitTime int32                  `protobuf:"varint,4,opt,name=estimated_wait_time,json=estimatedWaitTime,proto3" json:"estimated_wait_time,omitempty"` // seconds
	Error             string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LLMStatusResponse) Reset() {
	*x = LLMStatusResponse{}
	mi := &file_proto_search_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMStatusResponse) ProtoMessage() {}

func (x *LLMStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMStatusResponse.ProtoReflect.Descriptor instead.
func (*LLMStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{15}
}

func (x *LLMStatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LLMStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LLMStatusResponse) GetQueuePosition() int32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *LLMStatusResponse) GetEstimatedWaitTime() int32 {
	if x != nil {
		return x.EstimatedWaitTime
	}
	return 0
}

func (x *LLMStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LLMStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMStreamResponse) Reset() {
	*x = LLMStreamResponse{}
	mi := &file_proto_search_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMStreamResponse) ProtoMessage() {}

func (x *LLMStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMStreamResponse.ProtoReflect.Descriptor instead.
func (*LLMStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{16}
}

func (x *LLMStreamResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LLMStreamResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LLMStreamResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *LLMStreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LLMStreamResponse) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

var File_proto_search_proto protoreflect.FileDescriptor

const file_proto_search_proto_rawDesc = "" +
	"\n" +
	"\x12proto/search.proto\x12\x06search\"\x14\n" +
	"\x12HealthCheckRequest\"e\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"g\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vsafe_search\x18\x02 \x01(\bR\n" +
	"safeSearch\x12\x1f\n" +
	"\vnum_results\x18\x03 \x01(\x05R\n" +
	"numResults\"\x86\x01\n" +
	"\x0eSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.search.SearchResultR\aresults\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"q\n" +
	"\fSearchResult\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\x12\x1f\n" +
	"\vdisplay_url\x18\x04 \x01(\tR\n" +
	"displayUrl\"t\n" +
	"\x10SummarizeRequest\x12#\n" +
	"\roriginal_text\x18\x01 \x01(\tR\foriginalText\x12\x1c\n" +
	"\tstreaming\x18\x02 \x01(\bR\tstreaming\x12\x1d\n" +
	"\n" +
	"max_length\x18\x03 \x01(\x05R\tmaxLength\"\x9e\x01\n" +
	"\x11SummarizeResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x05R\n" +
	"tokensUsed\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\"|\n" +
	"\x17SummarizeStreamResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\"h\n" +
	"\x14ValidateInputRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x1f\n" +
	"\vsafe_search\x18\x03 \x01(\bR\n" +
	"safeSearch\"\x89\x01\n" +
	"\x15ValidateInputResponse\x12\x17\n" +
	"\ais_safe\x18\x01 \x01(\bR\x06isSafe\x12%\n" +
	"\x0esanitized_text\x18\x02 \x01(\tR\rsanitizedText\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"+\n" +
	"\x15SanitizeOutputRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"q\n" +
	"\x16SanitizeOutputResponse\x12%\n" +
	"\x0esanitized_text\x18\x01 \x01(\tR\rsanitizedText\x12\x1a\n" +
	"\bwarnings\x18\x02 \x03(\tR\bwarnings\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x86\x01\n" +
	"\n" +
	"LLMRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\bR\x06stream\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"\x81\x01\n" +
	"\vLLMResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06tokens\x18\x02 \x03(\tR\x06tokens\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1a\n" +
	"\bcomplete\x18\x05 \x01(\bR\bcomplete\"1\n" +
	"\x10LLMStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xb7\x01\n" +
	"\x11LLMStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0equeue_position\x18\x03 \x01(\x05R\rqueuePosition\x12.\n" +
	"\x13estimated_wait_time\x18\x04 \x01(\x05R\x11estimatedWaitTime\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x86\x01\n" +
	"\x11LLMStreamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition2\x90\x01\n" +
	"\rSearchService\x127\n" +
	"\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.search.HealthCheckRequest\x1a\x1b.search.HealthCheckResponse2\xec\x01\n" +
	"\x10InferenceService\x12@\n" +
	"\tSummarize\x12\x18.search.SummarizeRequest\x1a\x19.search.SummarizeResponse\x12N\n" +
	"\x0fSummarizeStream\x12\x18.search.SummarizeRequest\x1a\x1f.search.SummarizeStreamResponse0\x01\x12F\n" +
	"\vHealthCheck\x12\x1a.search.HealthCheckRequest\x1a\x1b.search.HealthCheckResponse2\xf6\x01\n" +
	"\rSafetyService\x12L\n" +
	"\rValidateInput\x12\x1c.search.ValidateInputRequest\x1a\x1d.search.ValidateInputResponse\x12O\n" +
	"\x0eSanitizeOutput\x12\x1d.search.SanitizeOutputRequest\x1a\x1e.search.SanitizeOutputResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.search.HealthCheckRequest\x1a\x1b.search.HealthCheckResponse2\x9f\x02\n" +
	"\x16LLMOrchestratorService\x129\n" +
	"\x0eProcessRequest\x12\x12.search.LLMRequest\x1a\x13.search.LLMResponse\x12@\n" +
	"\rStreamRequest\x12\x12.search.LLMRequest\x1a\x19.search.LLMStreamResponse0\x01\x12@\n" +
	"\tGetStatus\x12\x18.search.LLMStatusRequest\x1a\x19.search.LLMStatusResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.search.HealthCheckRequest\x1a\x1b.search.HealthCheckResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_search_proto_rawDescOnce sync.Once
	file_proto_search_proto_rawDescData []byte
)

func file_proto_search_proto_rawDescGZIP() []byte {
	file_proto_search_proto_rawDescOnce.Do(func() {
		file_proto_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)))
	})
	return file_proto_search_proto_rawDescData
}

var file_proto_search_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_search_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),      // 0: search.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 1: search.HealthCheckResponse
	(*SearchRequest)(nil),           // 2: search.SearchRequest
	(*SearchResponse)(nil),          // 3: search.SearchResponse
	(*SearchResult)(nil),            // 4: search.SearchResult
	(*SummarizeRequest)(nil),        // 5: search.SummarizeRequest
	(*SummarizeResponse)(nil),       // 6: search.SummarizeResponse
	(*SummarizeStreamResponse)(nil), // 7: search.SummarizeStreamResponse
	(*ValidateInputRequest)(nil),    // 8: search.ValidateInputRequest
	(*ValidateInputResponse)(nil),   // 9: search.ValidateInputResponse
	(*SanitizeOutputRequest)(nil),   // 10: search.SanitizeOutputRequest
	(*SanitizeOutputResponse)(nil),  // 11: search.SanitizeOutputResponse
	(*LLMRequest)(nil),              // 12: search.LLMRequest
	(*LLMResponse)(nil),             // 13: search.LLMResponse
	(*LLMStatusRequest)(nil),        // 14: search.LLMStatusRequest
	(*LLMStatusResponse)(nil),       // 15: search.LLMStatusResponse
	(*LLMStreamResponse)(nil),       // 16: search.LLMStreamResponse
}
var file_proto_search_proto_depIdxs = []int32{
	4,  // 0: search.SearchResponse.results:type_name -> search.SearchResult
	2,  // 1: search.SearchService.Search:input_type -> search.SearchRequest
	0,  // 2: search.SearchService.HealthCheck:input_type -> search.HealthCheckRequest
	5,  // 3: search.InferenceService.Summarize:input_type -> search.SummarizeRequest
	5,  // 4: search.InferenceService.SummarizeStream:input_type -> search.SummarizeRequest
	0,  // 5: search.InferenceService.HealthCheck:input_type -> search.HealthCheckRequest
	8,  // 6: search.SafetyService.ValidateInput:input_type -> search.ValidateInputRequest
	10, // 7: search.SafetyService.SanitizeOutput:input_type -> search.SanitizeOutputRequest
	0,  // 8: search.SafetyService.HealthCheck:input_type -> search.HealthCheckRequest
	12, // 9: search.LLMOrchestratorService.ProcessRequest:input_type -> search.LLMRequest
	12, // 10: search.LLMOrchestratorService.StreamRequest:input_type -> search.LLMRequest
	14, // 11: search.LLMOrchestratorService.GetStatus:input_type -> search.LLMStatusRequest
	0,  // 12: search.LLMOrchestratorService.HealthCheck:input_type -> search.HealthCheckRequest
	3,  // 13: search.SearchService.Search:output_type -> search.SearchResponse
	1,  // 14: search.SearchService.HealthCheck:output_type -> search.HealthCheckResponse
	6,  // 15: search.InferenceService.Summarize:output_type -> search.SummarizeResponse
	7,  // 16: search.InferenceService.SummarizeStream:output_type -> search.SummarizeStreamResponse
	1,  // 17: search.InferenceService.HealthCheck:output_type -> search.HealthCheckResponse
	9,  // 18: search.SafetyService.ValidateInput:output_type -> search.ValidateInputResponse
	11, // 19: search.SafetyService.SanitizeOutput:output_type -> search.SanitizeOutputResponse
	1,  // 20: search.SafetyService.HealthCheck:output_type -> search.HealthCheckResponse
	13, // 21: search.LLMOrchestratorService.ProcessRequest:output_type -> search.LLMResponse
	16, // 22: search.LLMOrchestratorService.StreamRequest:output_type -> search.LLMStreamResponse
	15, // 23: search.LLMOrchestratorService.GetStatus:output_type -> search.LLMStatusResponse
	1,  // 24: search.LLMOrchestratorService.HealthCheck:output_type -> search.HealthCheckResponse
	13, // [13:25] is the sub-list for method output_type
	1,  // [1:13] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_search_proto_init() }
func file_proto_search_proto_init() {
	if File_proto_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_search_proto_goTypes,
		DependencyIndexes: file_proto_search_proto_depIdxs,
		MessageInfos:      file_proto_search_proto_msgTypes,
	}.Build()
	File_proto_search_proto = out.File
	file_proto_search_proto_goTypes = nil
	file_proto_search_proto_depIdxs = nil
}
